### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by BrokenXZ** [lightbulblighter/Rboxlo#100]
I kept the domain as rboxlo.loc, but that doesn't connect. I do have all of the stuff in my hosts file
![image](https://user-images.githubusercontent.com/74031662/125176947-df787900-e1a5-11eb-84fc-cd7452ad3fce.png)
<br><br>
I also tried doing localhost, but that gave me this
![image](https://user-images.githubusercontent.com/74031662/125176963-03d45580-e1a6-11eb-8ae5-68df14cffcfb.png)
<br><br> 
I think that it's probably something wrong with my .env file, but I don't know what or how to fix it.

**Comment by lightbulblighter** [comment]
Why in the world did you send all of your encryption keys and passwords? Nevertheless the ciphersweet key is wrong. Pass 32 characters into a hex encoder. Delete this issue once you read this so your keys are kept private.

**Comment by BrokenXZ** [comment]
i have no idea how to delete issues, but i did put 32 characters into a hex encoder and it came out as 64

**Comment by IHATERBOXLO** [comment]
YOU NEED TO SHOOT YOURSELF

**Comment by IHATERBOXLO** [comment]
YOU CAN TALK YOU CAN TALK THROW HIS ASS OUT HES STILL A

**Comment by lightbulblighter** [comment]
> 
> 
> YOU NEED TO SHOOT YOURSELF

Please refer to the [contributing guide for civil discourse.](https://github.com/lightbulblighter/Rboxlo/blob/trunk/CONTRIBUTING.md)

**Comment by IHATERBOXLO** [comment]
Im sorry bruh please forgive me

**Comment by lightbulblighter** [comment]
> 
> 
> i have no idea how to delete issues, but i did put 32 characters into a hex encoder and it came out as 64

then use that

**Comment by BrokenXZ** [comment]
> > i have no idea how to delete issues, but i did put 32 characters into a hex encoder and it came out as 64
> 
> then use that

That's what I did

**Comment by lightbulblighter** [comment]
> 
> 
> > > i have no idea how to delete issues, but i did put 32 characters into a hex encoder and it came out as 64
> > 
> > 
> > then use that
> 
> That's what I did

Did you use the full 64 character key? Better yet; did you even start Rboxlo? When you run `docker compose up --build --force-recreate`, does rboxlo_server output "Started Rboxlo on port 80"?

If the issue turns out to be the ciphersweet key, you can run this for a valid format key that is also purely random.

```js
const sodium = require('sodium-native');
let keyMaterial = Buffer.alloc(32, 0);
sodium.randombytes_buf(keyMaterial);

console.log(keyMaterial.toString('hex'));
```
