### ISSUE TITLE
Help im trying to rename rboxlo

### ISSUE THREAD

**Issue by IHATERBOXLO** [lightbulblighter/Rboxlo#101]
So i used some tools called `grep` i cloned roblox and i tried making the name "Rniggalo" because im black and i though my blakc friends would enjoy it but fortunately it wouldnt work and it would only loade the page once i closed down the server @lightbulblighter Help please fix

- [ ] Bhb

**Comment by IHATERBOXLO** [comment]
BRUH FUCK YOU BRUH

**Comment by 39p** [comment]
Trollish. Dissapointed

**Comment by IHATERBOXLO** [comment]
Bros... will we ever get rniggalo
