### ISSUE TITLE
Database Access Denied Error.

### ISSUE THREAD

**Issue by ByCGS1999** [lightbulblighter/Rboxlo#102]
Hello, im obtaining this error everytime i make a search on the DB.
Any idea of how to fix this?

rboxlo_server    | (node:18) UnhandledPromiseRejectionWarning: Error: Access denied for user 'rboxloroot'@'172.18.0.3' (using password: YES)
rboxlo_server    |     at PromisePool.execute (/app/node_modules/mysql2/promise.js:358:22)
rboxlo_server    |     at Object.exports.run (/app/lib/base/sql.js:34:40)
rboxlo_server    |     at /app/lib/user.js:709:40
rboxlo_server    |     at new Promise (<anonymous>)
rboxlo_server    |     at Object.exports.createAccount (/app/lib/user.js:633:12)
rboxlo_server    |     at createAccount (/app/websites/eclipse/routes/account.js:43:10)
rboxlo_server    |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
rboxlo_server    |     at next (/app/node_modules/express/lib/router/route.js:137:13)
rboxlo_server    |     at exports.loggedOut (/app/lib/user.js:851:16)
rboxlo_server    |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
rboxlo_server    | (Use `node --trace-warnings ...` to show where the warning was created)
rboxlo_server    | (node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
rboxlo_server    | (node:18) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Thanks.

**Comment by ByCGS1999** [comment]
Somehow fixed alone.

**Comment by jaydengamble6** [comment]
@ByCGS1999 Hey, if you don't mind me asking, how did you fix this? I keep getting the 'Access denied for user' thing.

**Comment by ByCGS1999** [comment]
I actually dont remember how i fixed it since i had many troubles running the server.
If im not wrong its cause the database username and password doesn't match with the XAMPP SQL Process Name and Password
If you aren't minding on separating the database from the main server just don't portforward 3306 and use default username and password.

**Comment by jaydengamble6** [comment]
Ah right, and sorry but I'm a noob to SQL so not much makes sense to me, I'm gonna open an issue myself, maybe you can have a look at it to see if we're having the exact same issue.
