### ISSUE TITLE
How to deploy files? Cuz its not working for me

### ISSUE THREAD

**Issue by ByCGS1999** [lightbulblighter/Rboxlo#103]
Hello,
I recently got everything working so i started managing it. I entered inside the tootsie.
I compiled the Launcher, Arbitrer, etc.
When i tried to upload the files to the website it was not uploading them but there are no error logs.
Practicly they are not uploading and i dont have idea what the heck is happening
If you are asking for the size, they are in the range.
Player From 2016 (74mb)
Launcher(1.22mb)
Arbitrer(110kb).
None of these files are uploading

**Comment by lightbulblighter** [comment]
not implemented yet
