### ISSUE TITLE
Issues with signing up.

### ISSUE THREAD

**Issue by minerserver** [lightbulblighter/Rboxlo#106]
Hi when I try sign up on my rboxlo instance I get this error:
![image](https://user-images.githubusercontent.com/87002183/126136246-788443fc-3869-4e8b-921b-1e5186168b39.png)
and this prints out in the console:
rboxlo_server    | bad csrf

I am using the latest version.

**Comment by CozmoDev** [comment]
Im also getting the same issue. Did you fix it?

**Comment by lightbulblighter** [comment]
Is your session cookie or key secret filled out?

**Comment by lightbulblighter** [comment]
Merged into #107.
