### ISSUE TITLE
Error at setup

### ISSUE THREAD

**Issue by walker27460** [lightbulblighter/Rboxlo#110]
I'm trying to setup in docker but it says I don't have Python when it trying to `npm install`. 
it's they can't find some npm dependencies and fallbacking to build.
I modified Dockerfile to let docker `apk add python alpine-sdk` to install Python and build deps in `node:14-alpine` environment.

**Comment by GlowingUmbreon** [comment]
Why are you trying to use python? Rboxlo does not use python.

**Comment by walker27460** [comment]
it seems npm can't download some server dependencies and fallback to build and it needs python to build those dependencies.

**Comment by lightbulblighter** [comment]
That's weird. NPM should be able to build it fine. You may switch to the full node image by removing "alpine" in the FROM command. Would that work?

**Comment by Mantaraix** [comment]
That's weird. My nuts

**Comment by lightbulblighter** [comment]
> That's weird. My nuts

Hello @xlxi @brentdamage
