### ISSUE TITLE
This site can't be reached / Cannot GET 

### ISSUE THREAD

**Issue by roketlunchcer** [lightbulblighter/Rboxlo#113]
When I attempt to connect via www.rboxlo.loc, I get the error code 'DNS_PROBE_FINISHED_NXDOMAIN'
![err](https://user-images.githubusercontent.com/89823301/131434639-a176f45f-36e4-4cbb-b710-9462bc5ffb76.PNG)

When I attempt to connect via localhost 
![erro](https://user-images.githubusercontent.com/89823301/131434786-44759282-d60a-4903-8ea2-dc3b09e9d7d8.PNG)

Here is my .env file
![error](https://user-images.githubusercontent.com/89823301/131435227-40ef0545-5900-4989-b47f-6c0d2d0f68a2.PNG)

The ciphersweet key is 64 characters long, and I used the recommended hex encoder (Used just numbers no letters, unsure if that impacts it. I assume thats what made every 2nd character a 3)

**Thanks for taking the time to read this, I am very new to this so sorry for my ignorance.**
.
.
.
.
.
.
.

Microsoft Windows [Version 10.0.19041.1110]
(c) Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd /d Z:

Z:\>cd Z:\Games\Rboxlo\Rboxlo

Z:\Games\Rboxlo\Rboxlo>docker compose up --build --force-recreate
[+] Building 2.3s (19/19) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 34B                                                                                   0.0s
 => [internal] load metadata for docker.io/library/node:14-alpine                                                  2.1s
 => [ 1/14] FROM docker.io/library/node:14-alpine@sha256:b8d48b515e3049d4b7e9ced6cedbe223c3bc4a3d0fd02332448f3cdb  0.0s
 => [internal] load build context                                                                                  0.0s
 => => transferring context: 15.74kB                                                                               0.0s
 => CACHED [ 2/14] RUN mkdir /app                                                                                  0.0s
 => CACHED [ 3/14] WORKDIR /app                                                                                    0.0s
 => CACHED [ 4/14] COPY /Server/package*.json ./                                                                   0.0s
 => CACHED [ 5/14] COPY /Server ./                                                                                 0.0s
 => CACHED [ 6/14] RUN rm -rf ./node_modules                                                                       0.0s
 => CACHED [ 7/14] RUN npm install                                                                                 0.0s
 => CACHED [ 8/14] COPY /Branding/Artwork/Backdrops/Bricks.png ./wesbites/eclipse/public/img/art/bricks.png        0.0s
 => CACHED [ 9/14] COPY /Branding/Artwork/Backdrops/Main.png ./websites/eclipse/public/img/art/default.png         0.0s
 => CACHED [10/14] COPY /Branding/Logos/Primary/Big.png ./websites/eclipse/public/img/brand/large.png              0.0s
 => CACHED [11/14] COPY /Branding/Logos/Primary/Small.png ./websites/eclipse/public/img/brand/small.png            0.0s
 => CACHED [12/14] COPY /.git/refs/heads/trunk ./commit                                                            0.0s
 => CACHED [13/14] RUN chmod -R 777 /app                                                                           0.0s
 => CACHED [14/14] RUN adduser     --disabled-password     --gecos ""     --no-create-home     "app"               0.0s
 => exporting to image                                                                                             0.1s
 => => exporting layers                                                                                            0.0s
 => => writing image sha256:585302ccc4849d0277bcb175b5448894ccd281e7a4c53b0202db3d3f7924952c                       0.0s
 => => naming to docker.io/library/rboxlo_server                                                                   0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
[+] Running 2/2
 - Container rboxlo_database  Started                                                                              2.1s
 - Container rboxlo_server    Started                                                                              2.1s
Attaching to rboxlo_database, rboxlo_server
rboxlo_database  | 2021-08-31 03:03:41+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
rboxlo_database  | 2021-08-31 03:03:42+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.6.4+maria~focal started.
rboxlo_server    |
rboxlo_server    | > server@1.0.0 start /app
rboxlo_server    | > node index.js
rboxlo_server    |
rboxlo_database  | 2021-08-31  3:03:42 0 [Note] mysqld (server 10.6.4-MariaDB-1:10.6.4+maria~focal) starting as process 1 ...
rboxlo_database  | 2021-08-31  3:03:42 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
rboxlo_database  | 2021-08-31  3:03:42 0 [Note] InnoDB: Number of pools: 1
rboxlo_database  | 2021-08-31  3:03:42 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
rboxlo_database  | 2021-08-31  3:03:42 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
rboxlo_database  | 2021-08-31  3:03:42 0 [Note] InnoDB: Using Linux native AIO
rboxlo_database  | 2021-08-31  3:03:42 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
rboxlo_database  | 2021-08-31  3:03:42 0 [Note] InnoDB: Completed initialization of buffer pool
rboxlo_database  | 2021-08-31  3:03:42 0 [Note] InnoDB: 128 rollback segments are active.
rboxlo_database  | 2021-08-31  3:03:42 0 [Note] InnoDB: Creating shared tablespace for temporary tables
rboxlo_database  | 2021-08-31  3:03:42 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
rboxlo_database  | 2021-08-31  3:03:42 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
rboxlo_database  | 2021-08-31  3:03:42 0 [Note] InnoDB: 10.6.4 started; log sequence number 79152; transaction id 72
rboxlo_database  | 2021-08-31  3:03:42 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
rboxlo_database  | 2021-08-31  3:03:42 0 [Note] Plugin 'FEEDBACK' is disabled.
rboxlo_database  | 2021-08-31  3:03:42 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
rboxlo_database  | 2021-08-31  3:03:42 0 [Note] Server socket created on IP: '0.0.0.0'.
rboxlo_database  | 2021-08-31  3:03:42 0 [Note] Server socket created on IP: '::'.
rboxlo_database  | 2021-08-31  3:03:42 0 [Warning] 'proxies_priv' entry '@% root@database' ignored in --skip-name-resolve mode.
rboxlo_database  | 2021-08-31  3:03:42 0 [Note] mysqld: ready for connections.
rboxlo_database  | Version: '10.6.4-MariaDB-1:10.6.4+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
rboxlo_database  | 2021-08-31  3:03:42 0 [Note] InnoDB: Buffer pool(s) load completed at 210831  3:03:42
rboxlo_server    | Running Rboxlo on port 80

**Comment by GlowingUmbreon** [comment]
You need to edit your windows host files.
If you read [Guide.MD](https://github.com/lightbulblighter/Rboxlo/blob/trunk/Setup/GUIDE.md#troubleshooting) it says.
"Rboxlo is set up with `rboxlo.loc` everywhere as its default domain. If you are not able to access `rboxlo.loc` locally, copy and paste [this](https://raw.githubusercontent.com/lightbulblighter/Rboxlo/trunk/Setup/hosts) into [your hosts file.](https://www.whatsmydns.net/hosts-file.html)"

**Comment by roketlunchcer** [comment]
I was in the middle of writing a reply that I've already done that... but just checked my host file and found out that it did not save when I made the changes (my text edit software needed to be ran as admin)
Thanks for the reply!
