### ISSUE TITLE
Forum system

### ISSUE THREAD

**Issue by lightbulblighter** [lightbulblighter/Rboxlo#32]
A generic forum system for Rboxlo.

Forum tree:
1. Hub [title] (e.g "General Discussion")
2. Category [title, description] (e.g "Rboxlo Talk", "Talk about Rboxlo here")
3. Thread [title, content] (e.g "Help with DataStores", "How do I serialize a model?") 
4. Reply [content] (e.g "Use HttpService to encode in JSON")

Some ideas:
- Perhaps add the ability to use polls for threads?
- Markdown or bbCode?
- Frames?
- Secret threads? (private discussions between users?)
- Separate developer forum?

**Comment by lighterlightbulb** [comment]
Markdown will be used for the forums with no support for bbCode for the time being.

Frames are essentially iframes but for trusted sites only. Some things to think about with frames are:
- Does it scale well on mobile? Is it responsive?
- Security issues; can we uphold our security beliefs when interacting with websites that make heavy use of analytics (e.g Google?)
- Potential XSS? Can we add a website and trust them not to have their own XSS issues?
We will have to designate some power of our website to frames, which make it quite concerning.

**Comment by hitius2** [comment]
Why not just embed open graph instead of frames? It’d eliminate the possibility of xss and vulnerabilities

**Comment by lighterlightbulb** [comment]
Implementing open graph data in a post *could* work but is an entirely different system than what frames are supposed to be. I suppose it could be used as a replacement.

**Comment by lighterlightbulb** [comment]
In regards to a separate developer forum listed in the parent issue, this would require the forum system to be very modular and easily separable from the rest of the website which is not how other software in the website is designed as. Segregating the community into developers and playerrs should not exist anyway, so I am scrapping that idea for the time being.

**Comment by lighterlightbulb** [comment]
Polls will be added. Secret threads are scrapped as users can just communicate through off-site discourse mediums such as Discord or others.
