### ISSUE TITLE
Rboxlo.Arbiter

### ISSUE THREAD

**Issue by lightbulblighter** [lightbulblighter/Rboxlo#36]
General purpose Rboxlo Arbiter encompassing the features of the Roblox Arbiter but with extras such as Player and Studio hosting to provide proper hosting for 2012 and 2009 respectively, and a proper way for the website to talk to the Arbiter and vice versa. This will replace the GameServer and is necessary for Rboxlo servers to function.

**Comment by lighterlightbulb** [comment]
Arbiter should auto update RCC, Player, Studio, etc.etc.

**Comment by lightbulblighter** [comment]
Endpoints are getting implemented slowly but surely. The Arbiter itself should not be a pain once those are added.

**Comment by SpinnerChris** [comment]
ok so i built everything except for arbiter, it's giving me the error
The type or namespace name 'RccServiceSoap' could not be found (are you missing a using directive or an assembly reference?)	Rboxlo.Arbiter	C:\Users\bruh\Rboxlo\Arbiter\Client\RccService\Types\RccServiceProcess.cs	22	N/A

**Comment by lightbulblighter** [comment]
Ummm sorry bro but the issues category is just a laundry list of tasks for me to do. If you want to create an issue, create one, rather than comment on some random one.

Also i have solved that issue in the next commit. Will be pushed soon. BTW Rboxlo is not production-ready, *please* don't deploy it.

**Comment by SpinnerChris** [comment]
Thanks, I figured that this was the section to post bugs for Arbiter, with occasional updates, but it was a misinterpretation.  I'll create an issue next time.

**Comment by lightbulblighter** [comment]
Ya its np
