### ISSUE TITLE
Documentation/Wiki

### ISSUE THREAD

**Issue by lightbulblighter** [lightbulblighter/Rboxlo#45]
As of right now, Rboxlo has very little documentation besides the occasional code comment in some random endpoint that, at best, gives a very brief description of what the code line does but usually is just a vague comment. Rboxlo requires either one of the three:

- A GitHub Pages website documenting the codebase
- A README file in each project
- A GitHub Wiki page documenting the codebase

The best solution right now is a combination of options 2 and 3, being a README file in each project and a GitHub wiki for more complex topics.

**Comment by lighterlightbulb** [comment]
Fixed in next commit.

**Comment by lightbulblighter** [comment]
Re-opened because next commit has not been pushed yet.

- A GitHub Wiki page documenting the codebase has been implemented right now.
- A README file in each project will be pushed.

I also saw something about an `ARCHITECTURE.md`. Maybe that will be added too. Additionally, I've commented 99.9% of the source code (Arbiter, Website, Launcher).
