### ISSUE TITLE
Profanity filter

### ISSUE THREAD

**Issue by lightbulblighter** [lightbulblighter/Rboxlo#73]
Nowadays everybody is big boy. They say many bad words, to the detriment of a younger audience. As is customary in the old Roblox scene, we want to capture as much of our younger audience as possible. Roblonium excels in this.

Probably will use diogenesseesesssesess system or something like that.

**Comment by ObsidianPlague** [comment]
I know this sounds stupid but this should be an optional feature.

**Comment by lightbulblighter** [comment]
Indeed
