### ISSUE TITLE
ERROR: Service 'website' failed to build : COPY failed: file not found in build context or excluded by .dockerignore: stat .git/refs/heads/master: file does not exist

### ISSUE THREAD

**Issue by ObsidianPlague** [lightbulblighter/Rboxlo#76]
When I try running `docker-compose up` --build as said to do in the setup, i get this.
`Step 16/32 : COPY .git/refs/heads/master /var/www/Packaging/Hash
ERROR: Service 'website' failed to build : COPY failed: file not found in build context or excluded by .dockerignore: stat .git/refs/heads/master: file does not exist`

**Comment by lightbulblighter** [comment]
Did you clone using Git?

**Comment by ObsidianPlague** [comment]
oh im a dumbass i didn't think of doing that, sorry
