### ISSUE TITLE
issue setting up

### ISSUE THREAD

**Issue by TrueDubzy** [lightbulblighter/Rboxlo#77]
WARNING: Found orphan containers (blog, mailserver, website) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Building server
Sending build context to Docker daemon  6.179MB

Step 1/21 : FROM node:14-alpine
 ---> 001defe57f95
Step 2/21 : ARG SERVER_PORT
 ---> Using cache
 ---> fd08967fb55b
Step 3/21 : ENV DOCKER true
 ---> Using cache
 ---> da2b7ef54ddc
Step 4/21 : RUN mkdir /app
 ---> Using cache
 ---> fc125c185e67
Step 5/21 : WORKDIR /app
 ---> Using cache
 ---> 46a11d687095
Step 6/21 : COPY /Server/package*.json ./
 ---> Using cache
 ---> 00f40acbab4b
Step 7/21 : COPY /Server ./
 ---> Using cache
 ---> 7c02f425a459
Step 8/21 : RUN rm -rf ./node_modules
 ---> Using cache
 ---> a83d171ebd49
Step 9/21 : RUN npm install
 ---> Using cache
 ---> 54b8d5d94d82
Step 10/21 : COPY /Branding/Artwork/Backdrops/Bricks.png ./wesbites/eclipse/public/img/art/bricks.png
 ---> Using cache
 ---> 11cef2d78cd3
Step 11/21 : COPY /Branding/Artwork/Backdrops/Main.png ./websites/eclipse/public/img/art/default.png
 ---> Using cache
 ---> 18475dde2a4a
Step 12/21 : COPY /Branding/Logos/Primary/Big.png ./websites/eclipse/public/img/brand/large.png
 ---> Using cache
 ---> 7a783a13b76d
Step 13/21 : COPY /Branding/Logos/Primary/Small.png ./websites/eclipse/public/img/brand/small.png
 ---> Using cache
 ---> d05a1d99b06d
Step 14/21 : RUN mkdir ./packaging
 ---> Using cache
 ---> 1496287ad7c6
Step 15/21 : COPY /Packaging/Version ./packaging/version
 ---> Using cache
 ---> 999928a3fb45
Step 16/21 : COPY /.git/refs/heads/trunk ./packaging/commit
 ---> Using cache
 ---> 132a29bd1364
Step 17/21 : RUN chmod -R 777 /app
 ---> Using cache
 ---> d1b6d2769ceb
Step 18/21 : RUN adduser     --disabled-password     --gecos ""     --no-create-home     "app"
 ---> Using cache
 ---> b99d20c9c184
Step 19/21 : USER app
 ---> Using cache
 ---> c63113da1c6f
Step 20/21 : EXPOSE ${SERVER_PORT}
 ---> Using cache
 ---> 8a69d0d65cf6
Step 21/21 : CMD [ "node", "index.js" ]
 ---> Using cache
 ---> 99f16c4930fa
Successfully built 99f16c4930fa
Successfully tagged rboxlo_server:latest
Starting DubzysLego_server   ... done
Starting DubzysLego_database ... done
Attaching to DubzysLego_server, DubzysLego_database
DubzysLego_database | 2021-04-02 18:26:03+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.23-1debian10 started.
DubzysLego_database | 2021-04-02 18:26:03+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
DubzysLego_database | 2021-04-02 18:26:03+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.23-1debian10 started.
DubzysLego_database | 2021-04-02T18:26:04.409553Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.23) starting as process 1
DubzysLego_database | 2021-04-02T18:26:04.420889Z 1 [System] [MY-011012] [Server] Starting upgrade of data directory.
DubzysLego_database | 2021-04-02T18:26:04.421291Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
DubzysLego_database | 2021-04-02T18:26:04.524614Z 1 [ERROR] [MY-012224] [InnoDB] Tablespace flags are invalid in datafile: ./ibdata1, Space ID:0, Flags: 21. Please refer to http://dev.mysql.com/doc/refman/8.0/en/innodb-troubleshooting-datadict.html for how to resolve the issue.
DubzysLego_database | 2021-04-02T18:26:04.524806Z 1 [ERROR] [MY-012237] [InnoDB] Corrupted page [page id: space=0, page number=0] of datafile './ibdata1' could not be found in the doublewrite buffer.
DubzysLego_database | 2021-04-02T18:26:04.524953Z 1 [ERROR] [MY-012930] [InnoDB] Plugin initialization aborted with error Data structure corruption.
DubzysLego_server | /app/node_modules/ciphersweet-js/lib/keyprovider/stringprovider.js:25
DubzysLego_server |         buf.copy(this.symmetricKey, 0);
DubzysLego_server |             ^
DubzysLego_server |
DubzysLego_server | TypeError: buf.copy is not a function
DubzysLego_server |     at new StringProvider (/app/node_modules/ciphersweet-js/lib/keyprovider/stringprovider.js:25:13)
DubzysLego_server |     at Object.<anonymous> (/app/kryptshun.js:13:16)
DubzysLego_server |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
DubzysLego_server |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
DubzysLego_server |     at Module.load (internal/modules/cjs/loader.js:928:32)
DubzysLego_server |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
DubzysLego_server |     at Module.require (internal/modules/cjs/loader.js:952:19)
DubzysLego_server |     at require (internal/modules/cjs/helpers.js:88:18)
DubzysLego_server |     at Object.<anonymous> (/app/websites/eclipse/lib/user.js:13:19)
DubzysLego_server |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
DubzysLego_server exited with code 1
DubzysLego_database | 2021-04-02T18:26:05.024429Z 1 [ERROR] [MY-011013] [Server] Failed to initialize DD Storage Engine.
DubzysLego_database | 2021-04-02T18:26:05.025054Z 0 [ERROR] [MY-010020] [Server] Data Dictionary initialization failed.
DubzysLego_database | 2021-04-02T18:26:05.025709Z 0 [ERROR] [MY-010119] [Server] Aborting
DubzysLego_database | 2021-04-02T18:26:05.026686Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.23)  MySQL Community Server - GPL.
DubzysLego_database exited with code 1

**Comment by lightbulblighter** [comment]
The MySQL Docker image is very unstable, for whatever reason. In my experience, simply running the compose command again seems to fix any issues relating to a "corrupt" table.

For the ciphersweet issue, you are not providing a proper key that ciphersweet can create a buffer out of. Admittedly, this is my fault for not providing proper instructions on what key to use. The ciphersweet documentation provides this as the proper criteria for a key:

"You can pass a raw binary string, hex-encoded string, or base64url-encoded string to the StringProvider constructor, provided the decoded key is 256 bits." 

So just a key that is 256 bits in size that is encoded either in hex form or base64. It gives this as an example key: `4e1c44f87b4cdf21808762970b356891db180a9dd9850e7baf2a79ff3ab8a2fc`. Something similar to that should work.

**Comment by TrueDubzy** [comment]
i did what you said on the terminal responded with this,
Attaching to DubzysLego_database, DubzysLego_server
DubzysLego_database | 2021-04-02 18:43:07+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.23-1debian10 started.
DubzysLego_database | 2021-04-02 18:43:07+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
DubzysLego_database | 2021-04-02 18:43:07+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.23-1debian10 started.
DubzysLego_database | 2021-04-02T18:43:08.332501Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.23) starting as process 1
DubzysLego_database | 2021-04-02T18:43:08.344450Z 1 [System] [MY-011012] [Server] Starting upgrade of data directory.
DubzysLego_database | 2021-04-02T18:43:08.344536Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
DubzysLego_database | 2021-04-02T18:43:08.451688Z 1 [ERROR] [MY-012224] [InnoDB] Tablespace flags are invalid in datafile: ./ibdata1, Space ID:0, Flags: 21. Please refer to http://dev.mysql.com/doc/refman/8.0/en/innodb-troubleshooting-datadict.html for how to resolve the issue.
DubzysLego_database | 2021-04-02T18:43:08.451867Z 1 [ERROR] [MY-012237] [InnoDB] Corrupted page [page id: space=0, page number=0] of datafile './ibdata1' could not be found in the doublewrite buffer.
DubzysLego_database | 2021-04-02T18:43:08.452130Z 1 [ERROR] [MY-012930] [InnoDB] Plugin initialization aborted with error Data structure corruption.
DubzysLego_server | Running Dubzyslego on port 80
DubzysLego_database | 2021-04-02T18:43:08.947656Z 1 [ERROR] [MY-011013] [Server] Failed to initialize DD Storage Engine.
DubzysLego_database | 2021-04-02T18:43:08.948626Z 0 [ERROR] [MY-010020] [Server] Data Dictionary initialization failed.
DubzysLego_database | 2021-04-02T18:43:08.948922Z 0 [ERROR] [MY-010119] [Server] Aborting
DubzysLego_database | 2021-04-02T18:43:08.949563Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.23)  MySQL

**Comment by TrueDubzy** [comment]
also when i load page it give me in text only cannot GET /

**Comment by lightbulblighter** [comment]
Try deleting the Docker image and running the compose command again. If you're on Docker Desktop for Windows, just open the dashboard and click the remove button next to the container. If not, run `docker container ls` and then `docker container -rm [container_id]` for the ID of each container that is listed.

**Comment by TrueDubzy** [comment]
its not listing any containers, im using my personal ubuntu server

**Comment by TrueDubzy** [comment]
i couldnt find the cotainer id so i used the prune command and force "docker container prune"

**Comment by TrueDubzy** [comment]
i recompossed it and it started, however i use  a different domain and cant find the path manifest.json
