### ISSUE TITLE
"TypeError: Cannot read property 'copy' of undefined" error while trying to set up rboxlo

### ISSUE THREAD

**Issue by 0wG** [lightbulblighter/Rboxlo#84]
I've gotten the same error on Ubuntu Server 20.04 and Windows 10.
![120112612-c5be2d80-c133-11eb-8715-e5254ff68ba0](https://user-images.githubusercontent.com/80175409/120246796-8de7e080-c22e-11eb-8af8-399a98f3b826.png)

.env file:
```PRODUCTION=false
TZ=America/Edmonton
NAME=rboxlo
CURRENCY_NAME=rbux
SOCIAL_MEDIA=

STIPEND_TIMEOUT=3600
STIPEND_AMOUNT=120

PRIVATE_LOCKDOWN=false
PRIVATE_IMPLICATION=true
PRIVATE_REFERRAL=false
PRIVATE_INVITE_ONLY=false
PRIVATE_CLOSED=false

DB_PASSWORD=*
DB_USERNAME=root
DB_NAME=rboxlo

MAIL_PASSWORD=*
MAIL_USERNAME=no-reply

GOOGLE_RECAPTCHA_PUBLIC_KEY=
GOOGLE_RECAPTCHA_PRIVATE_KEY=
GOOGLE_ANALYTICS_ENABLED=false
GOOGLE_ANALYTICS_TAG=UA-00000

ENCRYPTION_KEY=*
CIPHERSWEET_KEY=

SERVER_HTTPS=false
SERVER_DOMAIN=rboxlo.loc
SERVER_CLOUDFLARE=false
SERVER_PORT=80
SERVER_X_POWERED_BY=true
SERVER_SESSION_SECRET=xabcx123x
SERVER_COOKIE_SECRET=xabcx123x
* means i censored it.```

**Comment by lightbulblighter** [comment]
CIPHERSWEET_KEY is left blank, causing an encryption error. You have to provide a 32-byte hex encoded key as your ciphersweet key. So just type 32 characters into something like [this](https://www.convertstring.com/EncodeDecode/HexEncode) and use it as your key. See if that works?

**Comment by 0wG** [comment]
Thanks, it works now.
