### ISSUE TITLE
"Cannot GET /" error when visiting Rboxlo website

### ISSUE THREAD

**Issue by 0wG** [lightbulblighter/Rboxlo#85]
Sorry for making this an issue now, I was very busy with school and other stuff.
![image](https://user-images.githubusercontent.com/80175409/121816488-56c3f700-cc52-11eb-941d-6d5fd7600f11.png)
I haven't done anything web development or docker related ever, so sorry if this seems like a stupid question.

**Comment by lightbulblighter** [comment]
Have you followed the instructions with modifying your hosts file? (You can edit it at `C:\Windows\System32\drivers\etc` if you're on Windows.)

**Comment by 0wG** [comment]
That worked, but now I have another issue with signing up.

Signing up on the homepage gets me this:
![image](https://user-images.githubusercontent.com/80175409/121825070-52eda000-cc65-11eb-86dd-7d09a5210044.png)

**Comment by lightbulblighter** [comment]
Great to hear that the hosts file was the issue. Could you file that as a separate issue? Unfortunately I can't address it at the moment as I don't have access to my environment, so a separate issue will be a great reminder. All the best!

**Comment by 0wG** [comment]
Alright.
