### ISSUE TITLE
Docker error YAY!

### ISSUE THREAD

**Issue by ByCGS1999** [lightbulblighter/Rboxlo#88]
I edit the .env file and i make everything. It seems to be good but when i use the command 'docker compose up --build' it starts building but when its finishing appears this: 
![image](https://user-images.githubusercontent.com/66258488/123682438-4c594e00-d84b-11eb-9e82-b026448eaa1f.png)

Any help for that or its just my docker is trash.
Thanks.

**Comment by lightbulblighter** [comment]
You didn't clone the repository with Git. Read step 1 of [the setup installation guide.](https://github.com/lightbulblighter/Rboxlo/blob/trunk/Setup/GUIDE.md)
