### ISSUE TITLE
Error on cyphersweet-js script

### ISSUE THREAD

**Issue by HowToE** [lightbulblighter/Rboxlo#89]
I compiled it and im obtaining this error when the server loads
I got NodeJS installed (v16.4.0) and also i tried with the version 14.17.1
Here is the env config:
PRODUCTION=false
TZ=America/Chicago
NAME=rboxlo
CURRENCY_NAME=rbux
SOCIAL_MEDIA=

TOOTSIE_PASSWORD=

STIPEND_TIMEOUT=86400
STIPEND_AMOUNT=25

PRIVATE_LOCKDOWN=false
PRIVATE_IMPLICATION=true
PRIVATE_REFERRAL=false
PRIVATE_INVITE_ONLY=false
PRIVATE_CLOSED=false

DB_PASSWORD=password
DB_USERNAME=root
DB_NAME=rboxlo

MAIL_PASSWORD=password
MAIL_USERNAME=no-reply

GOOGLE_RECAPTCHA_SITE_KEY=
GOOGLE_RECAPTCHA_PRIVATE_KEY=
GOOGLE_RECAPTCHA_ENABLED=false
GOOGLE_ANALYTICS_TAG=
GOOGLE_ANALYTICS_ENABLED=false

ENCRYPTION_KEY=C1P28H5MFP1MGI4590ORJYNGOEMGI458
CIPHERSWEET_KEY=Z02P5UBM5OD2P5IHHJG95OFM45923MHF

SERVER_HTTPS=false
SERVER_DOMAIN=rboxlo.loc
SERVER_CLOUDFLARE=false
SERVER_PORT=80
SERVER_X_POWERED_BY=true
SERVER_SESSION_SECRET=xabcx123x
SERVER_COOKIE_SECRET=xabcx123x

And here is the console log:
rboxlo_server    | /app/node_modules/ciphersweet-js/lib/keyprovider/stringprovider.js:25
rboxlo_server    |         buf.copy(this.symmetricKey, 0);
rboxlo_server    |             ^
rboxlo_server    |
rboxlo_server    | TypeError: buf.copy is not a function
rboxlo_server    |     at new StringProvider (/app/node_modules/ciphersweet-js/lib/keyprovider/stringprovider.js:25:13)
rboxlo_server    |     at Object.<anonymous> (/app/kryptshun.js:13:16)
rboxlo_server    |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
rboxlo_server    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
rboxlo_server    |     at Module.load (internal/modules/cjs/loader.js:950:32)
rboxlo_server    |     at Function.Module._load (internal/modules/cjs/loader.js:790:14)
rboxlo_server    |     at Module.require (internal/modules/cjs/loader.js:974:19)
rboxlo_server    |     at require (internal/modules/cjs/helpers.js:92:18)
rboxlo_server    |     at Object.<anonymous> (/app/websites/eclipse/lib/user.js:13:19)
rboxlo_server    |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
rboxlo_server    | npm ERR! code ELIFECYCLE
rboxlo_server    | npm ERR! errno 1
rboxlo_server    | npm ERR! server@1.0.0 start: `node index.js`
rboxlo_server    | npm ERR! Exit status 1
rboxlo_server    | npm ERR!
rboxlo_server    | npm ERR! Failed at the server@1.0.0 start script.
rboxlo_server    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
rboxlo_server exited with code 1

Thanks.

**Comment by lightbulblighter** [comment]
First off you shouldn't have posted your encryption keys here. I suggest deleting this issue after you read this.  

You aren't putting in a 32-character hex encoded string as your ciphersweet key.
