### ISSUE TITLE
Getting an error on a function

### ISSUE THREAD

**Issue by ByCGS1999** [lightbulblighter/Rboxlo#90]
Hello, im having a error on the cyphersweet module.
I have nodejs version 16.4.0
Can I need any dependencies that I don't have?
I tried changing the encryption key and cyphersweet key and nothing stills giving me that error (all the keys were 32 chars), also i tried searching google for the error and i didnt found any useful documentation about it.
This is the error:
rboxlo_server    | /app/node_modules/ciphersweet-js/lib/keyprovider/stringprovider.js:25
rboxlo_server    |         buf.copy(this.symmetricKey, 0);
rboxlo_server    |             ^
rboxlo_server    |
rboxlo_server    | TypeError: buf.copy is not a function

Any idea of how to fix it?

Thanks

**Comment by lightbulblighter** [comment]
did you hex encode your ciphersweet key?

**Comment by ByCGS1999** [comment]
yes, its encoded

**Comment by lightbulblighter** [comment]
Is your key of equal length to this string?
`4e1c44f87b4cdf21808762970b356891db180a9dd9850e7baf2a79ff3ab8a2fc`

**Comment by ByCGS1999** [comment]
Thanks the generator worked.
