### ISSUE TITLE
Container folder created by running 'docker compose up --build' its empty

### ISSUE THREAD

**Issue by ByCGS1999** [lightbulblighter/Rboxlo#91]
At this point i dont know if the problem is mine, from my docker or whatever but now this is happening to me
![image](https://user-images.githubusercontent.com/66258488/123925932-aeb96800-d98b-11eb-87d2-adeba6d96acd.png)

My theory its the file called Dockerfile its not running because it contains some copy instructions for the container and always i run it the container looks like this.
Server folder on container:
![image](https://user-images.githubusercontent.com/66258488/123926385-1cfe2a80-d98c-11eb-9533-121dd79c874d.png)
And the data folder inside server folder is completly empty.
And the root container folder:
![image](https://user-images.githubusercontent.com/66258488/123926498-38693580-d98c-11eb-86b1-4478160dd798.png)

Any suggestion of how to fix this?

**Comment by lightbulblighter** [comment]
that is intentional, copy the data folder from Server into there. This isn't documented yet though which is my fault, will be fixed soon

**Comment by ByCGS1999** [comment]
It didnt worked. Stills happening

**Comment by lightbulblighter** [comment]
What is the issue that is still happening?

**Comment by ByCGS1999** [comment]
The same. The website images are not loading

**Comment by lightbulblighter** [comment]
As of 6b8cc12, does the issue still exists? Make sure you follow each instruction in the [setup guide](https://github.com/lightbulblighter/Rboxlo/blob/trunk/Setup/GUIDE.md) carefully.

**Comment by lightbulblighter** [comment]
Fixed in afb4ec3; use the updated hosts file.
