### ISSUE TITLE
Issue with images not loading in

### ISSUE THREAD

**Issue by QuantumApex** [lightbulblighter/Rboxlo#97]
Hello I'm very interested in this project and I set it up on a ubuntu 21.04 server and the webpage is broken with images not loading in. There is a screenshot below, I'm new to github so excuse any mistakes I have made.
![image](https://user-images.githubusercontent.com/87092362/124811976-4dac0a00-df20-11eb-81ea-5746d8fac238.png)

**Comment by lightbulblighter** [comment]
Did you edit the Branding folder?

**Comment by QuantumApex** [comment]
No I followed the guide very carefully

**Comment by lightbulblighter** [comment]
Can you try the latest commit? In the screenshot it looks like an older one.

**Comment by QuantumApex** [comment]
did it again same issue it seems that git clone gets the old version for some reason

**Comment by QuantumApex** [comment]
how would I get the new version without git clone then

**Comment by lightbulblighter** [comment]
There is no way to get a new version that will function properly without cloning from Git. Please check your Git install-- this is a non-Rboxlo issue
