### ISSUE TITLE
Resources not loading in

### ISSUE THREAD

**Issue by Sqeky** [lightbulblighter/Rboxlo#99]
When I go on the webiste there are no images.
![Capture](https://user-images.githubusercontent.com/87245624/125176371-bb0da400-e187-11eb-9e4c-94b81129dc7d.PNG)

**Comment by lightbulblighter** [comment]
What commit are you running?

**Comment by Sqeky** [comment]
I'm running the latest commit.

**Comment by lightbulblighter** [comment]
Did you modify the Branding folder?

**Comment by Sqeky** [comment]
No I didn't.

**Comment by lightbulblighter** [comment]
Fixed in afb4ec3; use the updated hosts file.
